x-environment-database: &environment-database
  POSTGRES_USER: $DB_USERNAME
  POSTGRES_PASSWORD: $DB_PASSWORD
  POSTGRES_DB: $DB_DATABASE

volumes:
  postgres_volume:

services:
  db-postgres:
    image: postgres:14-alpine3.17
    environment:
      <<: *environment-database
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
